#config_version=5

hardware:
   platform: p_roc
   driverboards: sternWhitestar

p_roc:
  debug: true
  file_log: full

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

config:
 - sound_system.yaml
 - assets.yaml
 - sounds.yaml
 - videos.yaml
 - images.yaml
 - switches.yaml
 - coils.yaml
 - displays.yaml
 - flippers.yaml
 - ball_devices.yaml
 - autofire_coils.yaml
 - drop_targets.yaml
 - modes.yaml
 - variables.yaml

custom_code:
  - scriptlets.magnavuk.Magnavuk
  - scriptlets.magnaramp.Magnaramp

# Lights

lights:
  shoot_again:
    number: 44
