#config_version=5

hardware:
   platform: p_roc
   driverboards: sternWhitestar

game:
  balls_per_game: 3
  max_players: 4

kivy_config:
  kivy:
    log_enable: 1
    log_level: debug
    log_name: kivy.log
    log_dir: /Users/seanpaulfenton/src/mpf/tcm_pinball

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

config:
 - variables.yaml
 - settings.yaml
 - sound_system.yaml
 - assets.yaml
 - sounds.yaml
 - videos.yaml
 - images.yaml
 - switches.yaml
 - coils.yaml
 - displays.yaml
 - flippers.yaml
 - ball_devices.yaml
 - autofire_coils.yaml
 - drop_targets.yaml
 - diverters.yaml
 - lights.yaml
 - sequence_shots.yaml
 - widget_styles.yaml
 - shows.yaml
 - modes.yaml

custom_code:
  - scriptlets.magnavuk.Magnavuk
  - scriptlets.magnaramp.Magnaramp
  - scriptlets.mystery.Mystery
