#config_version=5

sounds:
  organ:
    file: organ.wav
  intro_jazz:
    file: ffab_loop.wav
    mode_end_action: stop
    volume: 0.5
  attract_dark:
    file: dark_open.wav
  open_speech:
    file: open_speech.wav
  franklin_cmon:
    file: franklin_cmon_franklin.wav
    volume: 0.9
  mask_slice:
    file: mask_slice.wav
    volume: 1.0
  franklin_hurry_up:
    file: franklin_hurry_up_v1.wav
    mode_end_action: stop
    volume: 1.0
  franklin_fun:
    file: franklin_fun.wav
    mode_end_action: stop
    volume: 1.0
  franklin_tantrum_ahh:
    file: franklin_tantrum_ahh.wav
    volume: 1.5
  franklin_tantrum_doh:
    file: franklin_tantrum_doh.wav
    volume: 1.5
  franklin_tantrum_fartsound:
    file: franklin_tantrum_fartsound.wav
    volume: 1.5
  franklin_tantrum_fartsound2:
    file: franklin_tantrum_fartsound2.wav
    volume: 1.5
  franklin_tantrum_fartsound3:
    file: franklin_tantrum_fartsound3.wav
    volume: 1.5
  franklin_tantrum_fartsound4:
    file: franklin_tantrum_fartsound4.wav
    volume: 1.5
  franklin_tantrum_fartsound5_double:
    file: franklin_tantrum_fartsound5_double.wav
    volume: 1.5
  franklin_tantrum_fartsound6:
    file: franklin_tantrum_fartsound6.wav
    volume: 1.5
  franklin_tantrum_fartsound7:
    file: franklin_tantrum_fartsound7.wav
    volume: 1.5
  franklin_tantrum_fun_trip:
    file: franklin_tantrum_fun_trip.wav
    volume: 1.5
  franklin_tantrum_laugh:
    file: franklin_tantrum_laugh.wav
    volume: 1.5
  franklin_tantrum_laugh2:
    file: franklin_tantrum_laugh2.wav
    volume: 1.5
  franklin_tantrum_laugh3:
    file: franklin_tantrum_laugh3.wav
    volume: 1.5
  franklin_tantrum_laugh4:
    file: franklin_tantrum_laugh4.wav
    volume: 1.5
  franklin_tantrum_laugh5:
    file: franklin_tantrum_laugh5.wav
    volume: 1.5
  franklin_tantrum_oww:
    file: franklin_tantrum_oww.wav
    volume: 1.5
  franklin_tantrum_uhh:
    file: franklin_tantrum_uhh.wav
    volume: 1.5
  franklin_arguement_cmon_push:
    file: franklin_arguement_cmon_push.wav
    volume: 1.5
  franklin_arguement_im_coming:
    file: franklin_arguement_im_coming.wav
    volume: 1.5
  franklin_arguement_sally:
    file: franklin_arguement_sally.wav
    volume: 1.5
  franklin_arguement_sally_stop:
    file: franklin_arguement_sally_stop.wav
    volume: 1.5
  franklin_boom_airgun:
    file: franklin_boom_airgun.wav
    volume: 1.5
  franklin_boom_airgun2:
    file: franklin_boom_airgun2.wav
    volume: 1.5
  franklin_crying:
    file: franklin_crying.wav
    volume: 1.5
  franklin_crying2:
    file: franklin_crying2.wav
    volume: 1.5
  franklin_frenzy4_better:
    file: franklin_frenzy4_better.wav
    volume: 1.5
  franklin_hey:
    file: franklin_hey.wav
    volume: 1.5
  franklin_jerry:
    file: franklin_jerry.wav
    volume: 1.5
  franklin_jerry2:
    file: franklin_jerry2.wav
    volume: 1.5
  franklin_sally:
    file: franklin_sally.wav
    volume: 1.5
  franklin_sallyyy_good:
    file: franklin_sallyyy_good.wav
    volume: 1.5
  franklin_shh_airgun:
    file: franklin_shh_airgun.wav
    volume: 1.5
  franklin_spit:
    file: franklin_spit.wav
    volume: 1.5
  franklin_gave_him_your_name:
    file: franklin_gave_him_your_name.wav
    volume: 1
  franklin_hes_gonna_kill_you:
    file: franklin_hes_gonna_kill_you.wav
    volume: 1
  frenzy:
    file: frenzy____LEGACY.wav
    volume: 1.5
  frenzy_bg_music:
    file: franklin_frenzy_v2.wav
    volume: 1
    mode_end_action: stop
  franklin_frenzy_bonus_v1:
    file: franklin_frenzy_bonus_v1.wav
    volume: 1
    mode_end_action: stop
  franklin_hurry_up_finish:
    file: franklin_hurry_up_finish.wav
    volume: 1
    mode_end_action: stop
  chainsaw_multiball_audio_v2:
    file: chainsaw_multiball_audio_v2.wav
    volume: 1
    mode_end_action: stop
  chainsaw_false_start:
    file: chainsaw_false_start.wav
    volume: 1
    mode_end_action: stop
  chainsaw_rev:
    file: chainsaw_rev_2.wav
    volume: 0.8
    mode_end_action: stop
  chainsaw_rev_2:
    file: chainsaw_rev_1.wav
    volume: 0.8
    mode_end_action: stop
  three_bells:
    file: three_bells.wav
    volume: 1
    mode_end_action: stop
  chainsaw_multiball_start:
    file: chainsaw_multiball_3_10frame.wav
    volume: 1
    mode_end_action: stop
  chainsaw_multiball_jackpot:
    file: jackpot_v1_2drip10fr v1.wav
    volume: 1
    mode_end_action: stop
  chainsaw_super_jackpot:
    file: super_jackpot_score_v1.wav
    volume: 1
    mode_end_action: stop
  space_jam_take_over_start:
    file: space_jam_takeover_v3_mbalt.wav
  space_jam_take_over_bg_music:
    file: space_jam_music_2.wav
    mode_end_action: stop
  space_jam_take_over_jackpot:
    file: space_jam_jackpot_rip1.wav
    mode_end_action: stop
  space_jam_take_over_super_jackpot:
    file: space_jam_super_jackpot_score_v3_2.wav
    mode_end_action: stop
  cow_moo:
    file: cow_1.wav
  slaugherhouse_gun:
    file: slaughtergun_v3.wav
  sftg_bump:
    file: sftg_bump_audio_v1_with_rise.wav
    volume: 1
  sftg_save:
    file: sftg_save_audio_v3_with_rise.wav
    volume: 1
  shoot_the_slaugherhouse:
    file: franklin_slaughter_room.wav
    volume: 1
  shovel_dig:
    file: shovel_sound.wav
    volume: 1
  swoosh_1:
    file: swoosh_4.wav
  mystery_sound:
    file: mystery_meat_6_score_v1.wav
  ding_1:
    file: sj_hit_2.wav
  ding_2:
    file: sj_hit.wav
