#config_version=5

switches:

  # -- Direct Switches --

  s_left_flipper:
    number: SD1
    tags: left_flipper
  s_left_flipper_eos:
    number: SD2
  s_right_flipper:
    number: SD3
    tags: right_flipper
  s_right_flipper_eos:
    number: SD4
  s_volume_red_button:
    number: SD6
  s_serve_cred_green_button:
    number: SD7
  s_begin_test_black_button:
    number: SD8

  # -- Matrix Switches --
  
  s_4th_coin_slot:
    number: S02
  s_6th_coin_slot:
    number: S03
  s_right_coin_slot:
    number: S04
  s_center_coin_slot:
    number: S05
  s_left_coin_slot:
    number: S06
  s_ball_trough_1:
    number: S11
  s_ball_trough_2:
    number: S12
  s_ball_trough_3:
    number: S13
  s_ball_trough_4:
    number: S14
  s_ball_vuk_opto:
    number: S15
  s_shooter_lane:
    number: S16
  s_3_bank_drop_bottom:
    number: S17
  s_3_bank_drop_mid:
    number: S18
  s_3_bank_drop_top:
    number: S19
  s_right_ramp_enter:
    number: S22
  s_right_ramp_exit:
    number: S23
  s_captive_ball_target:
    number: S24
    debounce: quick
    ignore_window_ms: 1000ms
  s_top_basket_enter:
    number: S25
    file_log: full
  s_top_basket_made:
    number: S27
  s_right_ramp_s_u_left:
    number: S28
  s_right_ramp_s_u_right:
    number: S29
  s_skill_shot_basket:
    number: S30
  s_chain_target_c:
    number: S33
    tags: chain_target_c
    debounce: quick
    ignore_window_ms: 1000ms
  s_chain_target_h:
    number: S34
    tags: chain_target_h
    debounce: quick
    ignore_window_ms: 1000ms
  s_chain_target_a:
    number: S35
    tags: chain_target_a
    debounce: quick
    ignore_window_ms: 1000ms
  s_chain_target_i:
    number: S36
    tags: chain_target_i
    debounce: quick
    ignore_window_ms: 1000ms
  s_chain_target_n:
    number: S37
    tags: chain_target_n
    debounce: quick
    ignore_window_ms: 1000ms
  s_saw_target_s:
    number: S38
    tags: saw_target_s
    debounce: quick
    ignore_window_ms: 1000ms
  s_saw_target_a:
    number: S39
    tags: saw_target_a
    debounce: quick
    ignore_window_ms: 1000ms
  s_saw_target_w:
    number: S40
    tags: saw_target_w
    debounce: quick
    ignore_window_ms: 1000ms
  s_super_duper_jackpot:
    number: S41
    tags: super_duper_jackpot
    debounce: quick
    ignore_window_ms: 1000ms
  s_extra_ball:
    number: S42
    tags: extra_ball
    debounce: quick
    ignore_window_ms: 1000ms
  s_right_orbit_top:
    number: S43
  s_right_orbit_bottom:
    number: S44
  s_jump_ball_vuk:
    number: S45
  s_sawyer_house_vuk:
    number: S46
  s_left_orbit_bottom:
    number: S47
  s_left_orbit_top:
    number: S48
  s_top_turbo_bumper:
    number: S49
  s_left_turbo_bumper:
    number: S50
  s_right_turbo_bumper:
    number: S51
  s_start:
    number: S54
    tags: start
  s_slam_tilt:
    number: S55
  s_plumb_bob_tilt:
    number: S56
  s_left_outlane:
    number: S57
  s_left_return_lane:
    number: S58
  s_left_slingshot:
    number: S59
  s_right_outlane:
    number: S60
  s_right_return_lane:
    number: S61
  s_right_slingshot:
    number: S62
