#config_version=5

machine_vars:
  magnavuk_auto_fire:
    initial_value: 1
  mask_completion_count_for_mask_making:
    initial_value: 3

player_vars:
  mask_completion_total:
    initial_value: 0
  mask_making_countdown_value:
    initial_value: 10
  franklin_hurry_up_countdown_value:
    initial_value: 10
  v_franklin_left_hit_total:
    initial_value: 0
  v_franklin_right_hit_total:
    initial_value: 0
