#config_version=5

machine_vars:
  magnavuk_auto_fire:
    initial_value: 1
  mask_completion_count_for_mask_making:
    initial_value: 3

player_vars:
  mask_completion_total:
    initial_value: 0
  mask_making_countdown_value:
    initial_value: 10
  franklin_hurry_up_countdown_add_value:
    initial_value: 0
  franklin_hurry_up_countdown_value:
    initial_value: 10
  franklin_hurry_up_countdown_holder_value:
    initial_value: 10
  franklin_total_completions:
    initial_value: 0
  v_franklin_left_hit_total:
    initial_value: 0
  v_franklin_right_hit_total:
    initial_value: 0
  v_chainsaw_multiball_active:
    initial_value: 0
  v_chainsaw_c_collected:
    initial_value: 0
  v_chainsaw_h_collected:
    initial_value: 0
  v_chainsaw_a_collected:
    initial_value: 0
  v_chainsaw_i_collected:
    initial_value: 0
  v_chainsaw_n_collected:
    initial_value: 0
  v_chainsaw_s_collected:
    initial_value: 0
  v_chainsaw_a2_collected:
    initial_value: 0
  v_chainsaw_w_collected:
    initial_value: 0
  v_chainsaw_all_collected:
    initial_value: 0
  v_chainsaw_jackpot_captive_ball_collected:
    initial_value: 0
  v_chainsaw_jackpot_left_ramp_collected:
    initial_value: 0
  v_chainsaw_jackpot_left_orbit_collected:
    initial_value: 0
  v_chainsaw_jackpot_right_ramp_collected:
    initial_value: 0
  v_chainsaw_jackpot_slaughter_house_collected:
    initial_value: 0
  v_chainsaw_jackpot_right_orbit_collected:
    initial_value: 0
  v_chainsaw_super_jackpot_lit:
    initial_value: 0
  v_cs_multiball_completion_counter_count:
    initial_value: 0
  v_space_jam_takeover_ready:
    initial_value: 0
  v_mystery_meater_count:
    initial_value: 0
  v_mystery_meater_width:
    initial_value: 0.0
    value_type: float
